// automatically generated by the FlatBuffers compiler, do not modify

package com.zoniklalessimo.seatingplanner.schema;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StudentSet extends Table {
  public static StudentSet getRootAsStudentSet(ByteBuffer _bb) { return getRootAsStudentSet(_bb, new StudentSet()); }
  public static StudentSet getRootAsStudentSet(ByteBuffer _bb, StudentSet obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public StudentSet __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String title() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer titleAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer titleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public Student students(int j) { return students(new Student(), j); }
  public Student students(Student obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int studentsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createStudentSet(FlatBufferBuilder builder,
      int titleOffset,
      int studentsOffset) {
    builder.startObject(2);
    StudentSet.addStudents(builder, studentsOffset);
    StudentSet.addTitle(builder, titleOffset);
    return StudentSet.endStudentSet(builder);
  }

  public static void startStudentSet(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addTitle(FlatBufferBuilder builder, int titleOffset) { builder.addOffset(0, titleOffset, 0); }
  public static void addStudents(FlatBufferBuilder builder, int studentsOffset) { builder.addOffset(1, studentsOffset, 0); }
  public static int createStudentsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startStudentsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endStudentSet(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishStudentSetBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedStudentSetBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

